#!/usr/bin/env python

import sys
from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone='visual_servoing_teleop.visual_servoing_teleop_plugin.VisualServoingTeleopPlugin'))
